@startuml
'https://plantuml.com/class-diagram

title 责任链模式（职责链）

class Client{}

abstract class Handler{
    - successor:Handler
    # handleRequest()
}

class ConcreteHandlerA extends Handler{}

class ConcreteHandlerB extends Handler{}

Handler "successor" o-- Handler

Client ..> Handler

@enduml