@startuml
'https://plantuml.com/class-diagram

interface QueueConvertStrategy{
    convert(T data) : T
}

class ListQueueConvertStrategy{
    convert(T data) : T
}

class Context {
    QueueConvertStrategy strategy
    setStrategy(Strategy strategy)
    execute(T data)
}

QueueConvertStrategy <|.. ListQueueConvertStrategy
QueueConvertStrategy <.. Context
@enduml
