@startuml
'https://plantuml.com/class-diagram

class Convert{
    # Database data
    + dispose()
}

class TXTConvert extends Convert{}
class XMLConvert extends Convert{}
class PDFConvert extends Convert{}

interface Database{
    + getData();
}

class MySQL implements Database {}
class Oracle implements Database {}
class SqlServer implements Database {}

Convert ..> Database
@enduml