@startuml
'https://plantuml.com/class-diagram
abstract class Aircraft{
    # Manufacturer imp
    + setImp(Manufacturer imp)
    + doSomething()
}

class Passenger extends Aircraft

interface Manufacturer{
    + sayHi()
}

class AirbusImp implements Manufacturer
class BoeingImp implements Manufacturer
class MacDonnellImp implements Manufacturer

Manufacturer <.. Aircraft

@enduml