@startuml
'https://plantuml.com/class-diagram

class 航天员{}
class 神州飞船{}

class 神州六号飞船 {
    Set<太阳能电池翼> 太阳翼
}

class 轨道舱{
    工作()
    休息()
}
class 返回舱{
    驾驭飞船()
}
class 推进舱{}
class 逃逸救生塔{
    逃生()
}
class 太阳能电池翼{
    供电()
}

神州飞船 <|-- 神州六号飞船
轨道舱 o-- 神州六号飞船
返回舱 o-- 神州六号飞船
推进舱 o-- 神州六号飞船
逃逸救生塔 o-- 神州六号飞船
太阳能电池翼 "n" o-- "1" 神州六号飞船

@enduml